### ISSUE TITLE
Databricks job error

### ISSUE THREAD

**Issue by npfp** [JDBraun/dbx_mws_example#1]
Hello,

I followed your example to setup our Databricks Resources from scratch.

Unfortunately, when trying to run a job defined using Databricks asset bundle, it fails with this output
```
run failed with error message
 Failed to reach the driver
```

In the event log, I can see this event
```
METASTORE_DOWN
```

and I also found this message in the log `Missing Credential Scope. Unity Credential Scope id not found in thread locals.` and this following exception:

```
[...]
org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:40)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:379)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:375)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:40)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:40)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:492)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$eagerlyExecuteCommands$1(QueryExecution.scala:347)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:436)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:347)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:284)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:281)
	at org.apache.spark.sql.Dataset.<init>(Dataset.scala:339)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:131)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1180)
	at org.apache.spark.sql.SparkSession.$anonfun$withActiveAndFrameProfiler$1(SparkSession.scala:1187)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:94)
	at org.apache.spark.sql.SparkSession.withActiveAndFrameProfiler(SparkSession.scala:1187)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:122)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$4(SparkSession.scala:959)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1180)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:947)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:982)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:1015)
	at org.apache.spark.sql.SQLContext.sql(SQLContext.scala:696)
	at com.databricks.backend.daemon.driver.DriverLocal.$anonfun$new$6(DriverLocal.scala:573)
	at org.apache.spark.SafeAddJarOrFile$.safe(SafeAddJarOrFile.scala:31)
	at com.databricks.backend.daemon.driver.DriverLocal.$anonfun$new$5(DriverLocal.scala:573)
	at com.databricks.sql.acl.CheckPermissions$.$anonfun$trusted$1(CheckPermissions.scala:2224)
	at com.databricks.sql.util.ThreadLocalTagger.withTag(QueryTagger.scala:62)
	at com.databricks.sql.util.ThreadLocalTagger.withTag$(QueryTagger.scala:59)
	at com.databricks.sql.util.QueryTagger$.withTag(QueryTagger.scala:132)
	at com.databricks.sql.acl.CheckPermissions$.trusted(CheckPermissions.scala:2224)
	at com.databricks.backend.daemon.driver.DriverLocal.$anonfun$new$4(DriverLocal.scala:572)
	at com.databricks.unity.EmptyHandle$.runWith(UCSHandle.scala:128)
	at com.databricks.backend.daemon.driver.DriverLocal.$anonfun$new$3(DriverLocal.scala:565)
	at scala.util.Using$.resource(Using.scala:269)
	at com.databricks.backend.daemon.driver.DriverLocal.$anonfun$new$2(DriverLocal.scala:564)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at com.databricks.backend.daemon.driver.DriverLocal.<init>(DriverLocal.scala:551)
	at com.databricks.backend.daemon.driver.PythonDriverLocalBase.<init>(PythonDriverLocalBase.scala:194)
	at com.databricks.backend.daemon.driver.JupyterDriverLocal.<init>(JupyterDriverLocal.scala:218)
	at com.databricks.backend.daemon.driver.PythonDriverWrapper.instantiateDriver(DriverWrapper.scala:975)
	at com.databricks.backend.daemon.driver.DriverWrapper.setupRepl(DriverWrapper.scala:417)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:291)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.datanucleus.exceptions.NucleusException: Attempt to invoke the "HikariCP" plugin to create a ConnectionPool gave an error : Failed to initialize pool: Could not connect to address=(host=********.eu-central-1.rds.amazonaws.com)(port=3306)(type=master) : Socket fail to connect to host:********.eu-central-1.rds.amazonaws.com, port:3306. connect timed out
	at org.datanucleus.store.rdbms.ConnectionFactoryImpl.generateDataSources(ConnectionFactoryImpl.java:232)
	at org.datanucleus.store.rdbms.ConnectionFactoryImpl.initialiseDataSources(ConnectionFactoryImpl.java:117)
	at org.datanucleus.store.rdbms.ConnectionFactoryImpl.<init>(ConnectionFactoryImpl.java:82)
	... 173 more
	[...]
	```

I wonder if it could be a cluster/vpc configuration issue. Would you have any clue on how I could fix this?

**Comment by npfp** [comment]
Just another example of duck debugging.

I found that the issue was indeed due to vpc issues related to the legacy hive Metastore. By following

https://medium.com/databricks-platform-sme/setup-an-ephemeral-metastore-for-the-uc-only-workspace-on-aws-f861bf4fe358

I managed to make the job run.

Would it make sense to add this config to the cluster policies directly in terraform?

```
{
  "spark_conf.spark.hadoop.javax.jdo.option.ConnectionURL": {
      "type": "fixed",
      "value": "jdbc:derby:memory:myInMemDB;create=true"
  },
  "spark_conf.spark.hadoop.javax.jdo.option.ConnectionDriverName": {
      "type": "fixed",
      "value": "org.apache.derby.jdbc.EmbeddedDriver"
  },
  "spark_conf.spark.hadoop.javax.jdo.option.ConnectionUserName": {
      "type": "fixed",
      "value": "<This is optional>"
  },
  "spark_conf.spark.hadoop.javax.jdo.option.ConnectionPassword": {
      "type": "fixed",
      "value": "<This is optional>"
  }
}
```

**Comment by JDBraun** [comment]
hey there - did you alter the network configuration? this is an example repo, so the set-up for the underlying network is fairly basic and should allow open egress to the HMS: 

https://github.com/JDBraun/dbx_mws_example/blob/020260b5d37b9454da5da780440f390d4932c3d9/repo/common_modules_cloud_provider/cloud_provider_network/cloud_provider_network.tf#L3

**Comment by npfp** [comment]
Yes you're right, I adapted the example to use an already existing VPC that didn't have the same network set-up.

**Comment by npfp** [comment]
Closing the issue as the issue was inherent to my implementation.
